### ISSUE TITLE
Railsの初歩を忘れていて、idカラムを追加しようとしてエラーで詰まった

### ISSUE THREAD

**Issue by Yukimarupie** [Yukimarupie/puffshare#2]
Letterモデル作成の際、idカラムは自動生成されるという初歩的なところを忘れていて、エラーで詰まったので、エラー文の記録を残しておきます。

主キーをを再定義するにはid: falseにしてくださいね?`と言われている気がします。

```
== 20210423054433 CreateLetters: migrating ====================================
-- create_table(:letters)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to create_table.
/app/db/migrate/20210423054433_create_letters.rb:4:in `block in change'
/app/db/migrate/20210423054433_create_letters.rb:3:in `change'
/app/bin/rails:5:in `<top (required)>'
/app/bin/spring:10:in `require'
/app/bin/spring:10:in `block in <top (required)>'
/app/bin/spring:7:in `<top (required)>'

Caused by:
ArgumentError: you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to create_table.
/app/db/migrate/20210423054433_create_letters.rb:4:in `block in change'
/app/db/migrate/20210423054433_create_letters.rb:3:in `change'
/app/bin/rails:5:in `<top (required)>'
/app/bin/spring:10:in `require'
/app/bin/spring:10:in `block in <top (required)>'
/app/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
ERROR: 1
```

####行った対処法
#####やったこと01) 一度`null: false`を消去してmigrateしてみる
=> 同じエラーが出ました。

#####やったこと02) エラー文でぐぐる
=> 結果: [Active Recordの変更点？しかヒットしませんでした](https://bityl.co/6W9R)

#####やったこと03) idカラムだけ一度消してmigrateしてみる
=> きちんとmigrateでき、schemaファイルにもDBテーブルが追加されました。

```scheme.rb
〜(省略)〜

  create_table "letters", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
    t.string "send_by", null: false
    t.string "send_to", null: false
    t.text "discription", null: false
    t.datetime "create_date", null: false
    t.string "api_status"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

〜(省略)〜
```

**Comment by Yukimarupie** [comment]
その後MySQLに接続して、テーブル構造を確認したところ、きちんとidカラムが自動生成されていたことを確認し、重複していただけか、と解決しました。
